export const ProjectData = [
  {
    img: "/upcoming.jpg",
    title: "Upcoming Project",
    techstack: "FrontEnd + BackEnd",
    live: "#",
    github: "#",
  },
  {
    img: "/ochi.png",
    title: "Ochi_Design FrontEnd",
    techstack: " React, Vite, Node, TailwindCSS, Framer Motion",
    live: "#",
    github: "https://github.com/Navneet0801/ochi_design_site",
  },
  {
    img: "/AiSumm.webp",
    title: "AI Article Summariser",
    techstack: "React, Redux, Article Summarizer API",
    live: "https://summarizearticle.netlify.app/",
    github: "https://github.com/pankajktech/ai-summariser",
  },
  {
    img: "/blogApp.webp",
    title: "MERN Blog App",
    techstack: "React, Node, Express, MongoDB, Tailwind CSS",
    live: "https://pankajktechblog.vercel.app/",
    github: "https://github.com/pankajktech/Blog-Website",
  },
  {
    img: "/blogApp.webp",
    title: "MERN Blog App",
    techstack: "React, Node, Express, MongoDB, Tailwind CSS",
    live: "https://pankajktechblog.vercel.app/",
    github: "https://github.com/pankajktech/Blog-Website",
  },
  {
    img: "/blogApp.webp",
    title: "MERN Blog App",
    techstack: "React, Node, Express, MongoDB, Tailwind CSS",
    live: "https://pankajktechblog.vercel.app/",
    github: "https://github.com/pankajktech/Blog-Website",
  },
  {
    img: "/blogApp.webp",
    title: "MERN Blog App",
    techstack: "React, Node, Express, MongoDB, Tailwind CSS",
    live: "https://pankajktechblog.vercel.app/",
    github: "https://github.com/pankajktech/Blog-Website",
  },
];
