export const ProjectData = [
  {
    img: "/upcoming.jpg",
    title: "Upcoming Project",
    techstack: " FrontEnd + BackEnd",
    live: "#",
    github: "#",
  },
  {
    img: "/chatpod.png",
    title: "Realtime Chat App",
    techstack: " React, Web Socket, Socket.io, Node, Express",
    live: "https://github.com/Navneet0801/ChatPod",
    github: "https://github.com/Navneet0801/ChatPod",
  },
  {
    img: "/ochi.png",
    title: "Ochi_Design FrontEnd",
    techstack: " React, Vite, Node, TailwindCSS, Framer Motion",
    live: "https://navneet0801.github.io/ochi_design_site/",
    github: "https://github.com/Navneet0801/ochi_design_site",
  },
  {
    img: "/weather.png",
    title: "Weather Detail Site",
    techstack: " HTML, CSS, JavaScript, NODE, NPM, API",
    live: "https://navneet0801.github.io/weather_details/",
    github: "https://github.com/Navneet0801/weather_details",
  },
  {
    img: "/tictactoe.png",
    title: "TIC TAC TOE Game",
    techstack: " HTML, CSS, JavaScript",
    live: "https://navneet0801.github.io/Tic-Tac-Toe/",
    github: "https://github.com/Navneet0801/Tic-Tac-Toe",
  },
  {
    img: "/Coffee.jpg",
    title: "Coffee Bill Generator",
    techstack: " JavaScript, Object Oriented Programming",
    live: "https://github.com/Navneet0801/Coffee_bill_calculator",
    github: "https://github.com/Navneet0801/Coffee_bill_calculator",
  },
  {
    img: "/simon.png",
    title: "Simon Game",
    techstack: " FrontEnd, HTML, CSS, JS",
    live: "https://github.com/Navneet0801/Coffee_bill_calculator",
    github: "https://navneet0801.github.io/Simon_Game/",
  },
];
